. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\vars.ps1
. $env:USERPROFILE\emudeck\settings.ps1
Set-Location $emulationPath
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\showListDialog.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\waitForWinRar.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\download.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\downloadCore.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\showNotification.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\moveFromTo.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\copyFromTo.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\waitForUser.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\sedFile.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\createLink.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\createLauncher.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\helperFunctions.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\showButtonQuestionImg.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\showButtonQuestion.ps1

. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckCemu.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckCitra.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckDolphin.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckDuckStation.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckPCSX2.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckRetroArch.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckRPCS3.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckTemplate.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckXemu.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckXenia.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckYuzu.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckRyujinx.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\EmuScripts\emuDeckPPSSPP.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\ToolScripts\emuDeckESDE.ps1
. $env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\ToolScripts\emuDeckSRM.ps1