. "$env:USERPROFILE\AppData\Roaming\EmuDeck\backend\vars.ps1"
. "$env:USERPROFILE\EmuDeck\settings.ps1"
. "$env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\createLink.ps1"
. "$env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\createLauncher.ps1"
. "$env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\helperFunctions.ps1"
. "$env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\ToolScripts\emuDeckSaveSync.ps1"
. "$env:USERPROFILE\AppData\Roaming\EmuDeck\backend\functions\emulatorInit.ps1"