[general]
show_welcome = false

[general.misc]
skip_boot_anim = true

[input.bindings]
port1 = '03000000de280000ff11000001000000'

[display.ui]
fit = 'stretch'

[sys]
mem_limit = '128'

[sys.files]
bootrom_path = '/run/media/mmcblk0p1/Emulation/bios/mcpx_1.0.bin'
flashrom_path = '/run/media/mmcblk0p1/Emulation/bios/Complex_4627v1.03.bin'
eeprom_path = '/run/media/mmcblk0p1/Emulation/saves/xemu/eeprom.bin'
hdd_path = '/run/media/mmcblk0p1/Emulation/saves/xemu/xbox_hdd.qcow2'
