name: CI

on:
  push:
    branches: [main, beta, dev]
  pull_request:
    branches: [main, beta, dev]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  PSScriptAnalyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
